mkdir hello-world

cd hello-worldgit initconsole.log("Hello World!");git add .

git commit -m "Initial commit"git remote add origin <https://github.com/><your-username>/<your-repo-name>.gitgit push -u origin master
